server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
        ddl-auto: update
auth:
  seconds-valid: 600
  secret: gw3lyhntu40ex30yzuiymrpcrpq6tpajhw1hgitti87e2rpca6